#!/usr/bin/env node

/**
 * confd-watch service for hhrpro
 *
 * This service will watch change in the etcd service running on the host
 * On change of the key /service/queue, this service will update the /etc/hosts file
 *
 * The service watches only changes for the queue instance
 */
var Etcd = require('node-etcd'),
    program = require('commander'),
    fs = require('fs'),
    pkg = require("./package.json"),
    swig = require('swig'),
    moment = require('moment'),
    exec = require('child_process').exec;

var conf = { HHRPro: {} };

program
	.version( pkg.version )
	.option('-h, --host [value]','etcd server [172.17.42.1]','172.17.42.1')
	.parse(process.argv);

console.log( "etcd server : ", program.host );

etcd = new Etcd( program.host, '4001' );
swig.setDefaults( { cache: false } );

var loop = setInterval( getConf, 5000 );

function updateHost(conf) {
	var data = { queue: null };

	if( !fs.existsSync('/etc/hosts.orig') ) {
		fs.writeFileSync('/etc/hosts.orig', fs.readFileSync('/etc/hosts'));
	}
	
	fs.writeFileSync('/etc/hosts', fs.readFileSync('/etc/hosts.orig'));
	if(conf.queue) {
		fs.appendFileSync('/etc/hosts', conf.queue.ip+"\t"+"queue"+"\n" )
	}
	console.log(moment().toISOString()+" /etc/hosts updated");
}

function getConf() {
	etcd.get('/services', { recursive: true }, function( err, resp ) {
		if(err) {
			console.error("error ",err);
		} else {
			clearInterval(loop);
			if( resp.node.nodes ) {
				resp.node.nodes.forEach( function(node) {
					if( node.key === "/services/queue") {
						conf.queue = JSON.parse(node.value);
					}
				});
			}
			updateHost(conf);
			
			watcher = etcd.watcher("/services", null, { recursive:true} );
			watcher.on("change", function( action ) {
				switch( action.action ) {
					case 'set':
						if( action.node.key === "/services/queue") {
							console.log(moment().toISOString()+"\t"+action.node.key+" change to "+action.node.value);
							conf.queue = JSON.parse(action.node.value);
						}
						break;
					case 'delete':
						if( action.node.key === "/services/queue") {
							console.log(moment().toISOString()+"\t"+action.node.key+" is down ");
							conf.queue = null;
						}
						break;
				}
				updateHost(conf);
			});
		}
	});
}
