#!/bin/bash

function usage {
    echo "usage : initDB hostIP dbName"
    echo "    where hostIP is the ip address of the server"
    echo "    and where dbName is name of the database ( by eg : physiodom )"
    exit 
}

if [ -z $1 ]; then
    usage
else
    IP=$1
fi

if [ -z $2 ]; then
        usage
else
        DBNAME=$2
fi

echo "${MONGODOCKER} ${IP}"

mongo ${IP}/${DBNAME} --eval "db.dropDatabase()"
mongoimport -h ${IP} -d ${DBNAME} --drop -c lists --file lists.json --jsonArray
mongoimport -h ${IP} -d ${DBNAME} --drop -c questionnaires --file questionnaires.json --jsonArray
mongoimport -h ${IP} -d ${DBNAME} --drop -c menus --file menus.json --jsonArray
mongoimport -h ${IP} -d ${DBNAME} --drop -c professionals --file professionals.json --jsonArray
mongoimport -h ${IP} -d ${DBNAME} --drop -c account --file account.json --jsonArray
mongoimport -h ${IP} -d ${DBNAME} --drop -c specialRights --file specialRights.json --jsonArray

echo "database initialized"

