#!/bin/bash

if (( $# < 2 ))
then
  echo "Usage: restoreDB ARCHIVE MONGOHOST [MONGODB]"
  echo "  Where :"
  echo "   - ARCHIVE   is the path of tar.bz2 file ( by example hhrpro-test-20150526154731.tar.bz2 )"
  echo "   - MONGOHOST is the name of the mongodb docker ( by example: mongo )"
  echo "   - MONGODB   is the name of the database to restore ( by example: hhrpro-test )"
  echo "     by default the name of the database is extracted from the dump file"
  echo ""
  exit 0
fi

ARCHIVE=$1
MONGOHOST=$2
if (( $# == 3 ))
then
	MONGODEST=$3
else
	MONGODEST=""
fi

tar -xvjf ${ARCHIVE} > /dev/null
for FILE in dump/*; do MONGODB=$( basename ${FILE} ); break; done

if [ -z "${MONGODEST}" ]
then
	MONGODEST=${MONGODB}
fi

/usr/bin/mongorestore --host $(docker-ip ${MONGOHOST}) --drop -d ${MONGODEST} dump/${MONGODB} > /dev/null
