#!/bin/bash

### BEGIN INIT INFO
# Provides:             PhysioDOM server
# Required-Start:       $remote_fs
# Required-Stop:        $remote_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    PhysioDOM sever
# Description:          start the PhysioDOM Portal and web Service
### END INIT INFO

. /lib/lsb/init-functions
. /etc/environment

PROGDIR="/home/http/physiodom"
PROG="server/server.js"
LOGDIR="/home/http/physiodom/log"
FOREVER="/opt/node/bin/forever"
DEBUG=""

if [ ! -d ${LOGDIR} ]
then
    install -d ${LOGDIR} -m 755
fi

case "$1" in
        start)
                if ( $FOREVER list | grep -q ${PROGDIR}/${PROG} ) ; then
                   log_warning_msg "service is already running"
                   exit 1
                fi
                $FOREVER start -a -l ${LOGDIR}/physiodom.log \
                       ${PROGDIR}/${PROG} -p 8001
                log_end_msg 0
                ;;
        stop)
                $FOREVER stop ${PROGDIR}/${PROG}
                log_end_msg 0
                ;;
        restart)
                $FOREVER stop ${PROGDIR}/${PROG}    
                $FOREVER start -a -l ${LOGDIR}/physiodom.log \
                         ${PROGDIR}/${PROG} -p 8001
                log_end_msg 0
                ;;
        status)
                if ( $FOREVER list | grep -q ${PROGDIR}/${PROG} ) ; then
                   log_success_msg "service is running"
                else
                   log_warning_msg "service is not running"
                fi 
                ;;
        *)
                log_success_msg "Usage: /etc/init.d/initSI {start|stop|reload|status}"
                exit 1
esac